name: Test on Pull Request and Push Docker on Merge

on:
  pull_request:
    branches:
      - main  # Run tests for PRs targeting the main branch
    types: 
      - closed  # Trigger when the pull request is closed (merged)

jobs:
  test:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.pull_request.state == 'open'  # Ensure it runs only on open PRs

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Run tests
      run: python -m unittest discover -s . -p "test_*.py"

  build-and-push:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.pull_request.merged == true  # Ensure it runs only when the PR is merged

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Docker login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/docker_and_github_actions_test:latest
