name: Test and push Docker Image

on:
 push:
   braches: ['main']
 pull_request:
   branches: ["main"]


jobs:
   test-and-build:
     runs-on: ubuntu-latest
     steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

        -name: Run tests
         run: python -m unittest discover -s . -p "test_*.py"
         
        -name: Docker login
         if: success()
         uses: docker/login-action@v2
         with:
           username: ${{secrets.DOCKER_USERNAME}} 
           password: ${{secrets.DOCKER_PASSWORD}}

        - name: build and push
          if: success()
          uses: docker/build-push-action@v4
          with:
            context:
            push : true
            tags: ${{secrets.DOCKER_USERNAME}} /docker_and_gihub_actions_test  
